import { describe, expect, it } from "vitest";
import { androidTargets, androidVersion, parseProperties } from "../scripts/android-config.mjs";

describe("Android distribution configuration", () => {
  it("decodes SDK paths generated by Android Studio on Windows", () => {
    expect(
      parseProperties(String.raw`# local SDK
sdk.dir=C\:\\Users\\Ana\\Android SDK
name=Ana\u0219a`),
    ).toEqual({ "sdk.dir": "C:\\Users\\Ana\\Android SDK", name: "Anașa" });
  });

  it("rejects invalid versions and artifact names before invoking a build", () => {
    expect(androidVersion("versionCode=2\nversionName=1.0.1")).toEqual({ code: 2, name: "1.0.1" });
    for (const version of [
      "versionCode=0\nversionName=1.0",
      "versionCode=1.5\nversionName=1.0",
      "versionCode=2100000001\nversionName=1.0",
      "versionCode=1\nversionName=../wrong",
    ]) {
      expect(() => androidVersion(version)).toThrow();
    }
  });

  it("builds a Play bundle and direct APK using their respective release profiles", () => {
    const targets = androidTargets("release");
    expect(
      targets.map(({ task, distribution, extension }) => [task, distribution, extension]),
    ).toEqual([
      [":app:assembleRelease", "apk", "apk"],
      [":app:bundleRelease", "play", "aab"],
    ]);
    expect(targets.every(({ suffix }) => suffix === "")).toBe(true);
    expect(androidTargets("apk")).toEqual([targets[0]]);
    expect(androidTargets("aab")).toEqual([targets[1]]);
    expect(() => androidTargets("web")).toThrow();
  });

  it("keeps a debug APK clearly separate from release artifacts", () => {
    const [debug] = androidTargets("debug-apk");
    expect(debug?.task).toBe(":app:assembleDebug");
    expect(debug?.source).toBe("apk/debug/app-debug.apk");
    expect(debug?.suffix).toBe("-debug");
  });
});
